name: test
on:
  push:

permissions: {}

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Free Disk Space (Ubuntu)
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf /opt/hostedtoolcache
      - name: Check Disk Space
        run: df -h
